In [1]:
# import libraries
import pandas as pd

import nltk

from nltk.sentiment.vader import SentimentIntensityAnalyzer

from nltk.corpus import stopwords

from nltk.tokenize import word_tokenize

from nltk.stem import WordNetLemmatizer


# download nltk corpus (first time only)
import nltk

nltk.download('all')




# Load the amazon review dataset

df = pd.read_csv('https://raw.githubusercontent.com/pycaret/pycaret/master/datasets/amazon.csv')

df

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/abc.zip.
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/alpino.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_ru.zip.
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/basque_grammars.zip.
[nltk_data]    | Downloading package bcp47 to /root/nltk_data...
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   U

reviewText  Positive
0      This is a one of the best apps acording to a b...         1
1      This is a pretty good version of the game for ...         1
2      this is a really cool game. there are a bunch ...         1
3      This is a silly game and can be frustrating, b...         1
4      This is a terrific game on any pad. Hrs of fun...         1
...                                                  ...       ...
19995  this app is fricken stupid.it froze on the kin...         0
19996  Please add me!!!!! I need neighbors! Ginger101...         1
19997  love it!  this game. is awesome. wish it had m...         1
19998  I love love love this app on my side of fashio...         1
19999  This game is a rip off. Here is a list of thin...         0

[20000 rows x 2 columns]

In [2]:
df['reviewText']


0        This is a one of the best apps acording to a b...
1        This is a pretty good version of the game for ...
2        this is a really cool game. there are a bunch ...
3        This is a silly game and can be frustrating, b...
4        This is a terrific game on any pad. Hrs of fun...
                               ...                        
19995    this app is fricken stupid.it froze on the kin...
19996    Please add me!!!!! I need neighbors! Ginger101...
19997    love it!  this game. is awesome. wish it had m...
19998    I love love love this app on my side of fashio...
19999    This game is a rip off. Here is a list of thin...
Name: reviewText, Length: 20000, dtype: object

In [3]:
s = []
for i in df['reviewText']:
  #print(i)
  s.append(i.lower())
print(s)
df['reviewText'] = s
df['reviewText']

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



0        this is a one of the best apps acording to a b...
1        this is a pretty good version of the game for ...
2        this is a really cool game. there are a bunch ...
3        this is a silly game and can be frustrating, b...
4        this is a terrific game on any pad. hrs of fun...
                               ...                        
19995    this app is fricken stupid.it froze on the kin...
19996    please add me!!!!! i need neighbors! ginger101...
19997    love it!  this game. is awesome. wish it had m...
19998    i love love love this app on my side of fashio...
19999    this game is a rip off. here is a list of thin...
Name: reviewText, Length: 20000, dtype: object

In [4]:
nltk.download('stopwords')
from nltk.corpus import stopwords

stop_words = stopwords.words('english')
df['reviewText'] = df['reviewText'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop_words)]))
df

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


reviewText  Positive
0      one best apps acording bunch people agree bomb...         1
1      pretty good version game free. lots different ...         1
2      really cool game. bunch levels find golden egg...         1
3      silly game frustrating, lots fun definitely re...         1
4      terrific game pad. hrs fun. grandkids love it....         1
...                                                  ...       ...
19995  app fricken stupid.it froze kindle wont allow ...         0
19996  please add me!!!!! need neighbors! ginger1016!...         1
19997  love it! game. awesome. wish free stuff houses...         1
19998  love love love app side fashion story fights w...         1
19999  game rip off. list things make better&bull; fi...         0

[20000 rows x 2 columns]

In [5]:
import nltk
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
def lemmatize_words(text):
    words = text.split()
    words = [lemmatizer.lemmatize(word,pos='v') for word in words]
    return ' '.join(words)
df['reviewText'] = df['reviewText'].apply(lemmatize_words)
df

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


reviewText  Positive
0      one best apps acording bunch people agree bomb...         1
1      pretty good version game free. lot different l...         1
2      really cool game. bunch level find golden eggs...         1
3      silly game frustrating, lot fun definitely rec...         1
4      terrific game pad. hrs fun. grandkids love it....         1
...                                                  ...       ...
19995  app fricken stupid.it freeze kindle wont allow...         0
19996  please add me!!!!! need neighbors! ginger1016!...         1
19997  love it! game. awesome. wish free stuff house ...         1
19998  love love love app side fashion story fight wo...         1
19999  game rip off. list things make better&bull; fi...         0

[20000 rows x 2 columns]

In [6]:
# initialize NLTK sentiment analyzer

analyzer = SentimentIntensityAnalyzer()


# create get_sentiment function

def get_sentiment(text):

    scores = analyzer.polarity_scores(text)

    sentiment = 1 if scores['pos'] > 0 else 0

    return sentiment




# apply get_sentiment function

df['sentiment'] = df['reviewText'].apply(get_sentiment)

df

reviewText  Positive  sentiment
0      one best apps acording bunch people agree bomb...         1          1
1      pretty good version game free. lot different l...         1          1
2      really cool game. bunch level find golden eggs...         1          1
3      silly game frustrating, lot fun definitely rec...         1          1
4      terrific game pad. hrs fun. grandkids love it....         1          1
...                                                  ...       ...        ...
19995  app fricken stupid.it freeze kindle wont allow...         0          1
19996  please add me!!!!! need neighbors! ginger1016!...         1          1
19997  love it! game. awesome. wish free stuff house ...         1          1
19998  love love love app side fashion story fight wo...         1          1
19999  game rip off. list things make better&bull; fi...         0          1

[20000 rows x 3 columns]

In [7]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(df['Positive'], df['sentiment']))

[[ 1093  3674]
 [  573 14660]]


In [8]:
from sklearn.metrics import classification_report

print(classification_report(df['Positive'], df['sentiment']))

              precision    recall  f1-score   support

           0       0.66      0.23      0.34      4767
           1       0.80      0.96      0.87     15233

    accuracy                           0.79     20000
   macro avg       0.73      0.60      0.61     20000
weighted avg       0.77      0.79      0.75     20000



In [9]:
# create preprocess_text function
def preprocess_text(text):

    # Tokenize the text

    tokens = word_tokenize(text.lower())




    # Remove stop words

    filtered_tokens = [token for token in tokens if token not in stopwords.words('english')]




    # Lemmatize the tokens

    lemmatizer = WordNetLemmatizer()

    lemmatized_tokens = [lemmatizer.lemmatize(token) for token in filtered_tokens]




    # Join the tokens back into a string

    processed_text = ' '.join(lemmatized_tokens)

    return processed_text

# apply the function df

df['reviewText'] = df['reviewText'].apply(preprocess_text)
df

reviewText  Positive  sentiment
0      one best apps acording bunch people agree bomb...         1          1
1      pretty good version game free . lot different ...         1          1
2      really cool game . bunch level find golden egg...         1          1
3      silly game frustrating , lot fun definitely re...         1          1
4      terrific game pad . hr fun . grandkids love . ...         1          1
...                                                  ...       ...        ...
19995  app fricken stupid.it freeze kindle wont allow...         0          1
19996  please add ! ! ! ! ! need neighbor ! ginger101...         1          1
19997  love ! game . awesome . wish free stuff house ...         1          1
19998  love love love app side fashion story fight wo...         1          1
19999  game rip . list thing make better & bull ; fir...         0          1

[20000 rows x 3 columns]

In [11]:
import numpy as np
a = np.eye(6,6)
print(a)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [12]:
a.reshape((3,-1))

array([[1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1.]])

In [13]:
import pandas as pd
obj2 = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"])
print(obj2)

d    4
b    7
a   -5
c    3
dtype: int64


In [14]:
print(obj2[["a", "b"]])

a   -5
b    7
dtype: int64


In [15]:
print(obj2[obj2>3])

d    4
b    7
dtype: int64
